"""Initial schema. Frozen independently of application models."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_crs', sa.Text(), nullable=True),
    sa.Column('measurement_crs', sa.Text(), nullable=True),
    sa.Column('measurement_method', sa.String(length=30), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_created_at'), 'uploaded_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_status'), 'uploaded_files', ['status'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('file_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('feature_index', sa.Integer(), nullable=False),
    sa.Column('source_feature_id', sa.String(length=255), nullable=True),
    sa.Column('geometry_type', sa.String(length=40), nullable=False),
    sa.Column('geometry_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'feature_index')
    )
    op.create_index(op.f('ix_features_file_id'), 'features', ['file_id'], unique=False)
    op.create_table('processing_events',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('file_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_events_file_id'), 'processing_events', ['file_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('feature_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('measurement_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('measurement_crs', sa.Text(), nullable=True),
    sa.Column('ellipsoid', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id')
    )
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_index(op.f('ix_processing_events_file_id'), table_name='processing_events')
    op.drop_table('processing_events')
    op.drop_index(op.f('ix_features_file_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_uploaded_files_status'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_created_at'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###

